<a href="https://colab.research.google.com/github/VEDAVYAS28/HillandValley/blob/main/Hill_and_Valley_Prediction_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('/content/hill and valley.csv')

In [4]:
 df.head()

V1        V2        V3        V4        V5        V6        V7  \
0     39.02     36.49     38.20     38.85     39.38     39.74     37.02   
1      1.83      1.71      1.77      1.77      1.68      1.78      1.80   
2  68177.69  66138.42  72981.88  74304.33  67549.66  69367.34  69169.41   
3  44889.06  39191.86  40728.46  38576.36  45876.06  47034.00  46611.43   
4      5.70      5.40      5.28      5.38      5.27      5.61      6.00   

         V8        V9       V10  ...       V92       V93       V94       V95  \
0     39.53     38.81     38.79  ...     36.62     36.92     38.80     38.52   
1      1.70      1.75      1.78  ...      1.80      1.79      1.77      1.74   
2  73268.61  74465.84  72503.37  ...  73438.88  71053.35  71112.62  74916.48   
3  37668.32  40980.89  38466.15  ...  42625.67  40684.20  46960.73  44546.80   
4      5.38      5.34      5.87  ...      5.17      5.67      5.60      5.94   

        V96       V97       V98       V99      V100  Class  
0     38.07     36.73     39.46     37.50     39.10      0  
1      1.74      1.80      1.78      1.75      1.69      1  
2  72571.58  66348.97  71063.72  67404.27  74920.24      1  
3  45410.53  47139.44  43095.68  40888.34  39615.19      0  
4      5.73      5.22      5.30      5.73      5.91      0  

[5 rows x 101 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Columns: 101 entries, V1 to Class
dtypes: float64(100), int64(1)
memory usage: 956.5 KB


In [6]:
df.describe()

V1             V2             V3             V4  \
count    1212.000000    1212.000000    1212.000000    1212.000000   
mean     8169.091881    8144.306262    8192.653738    8176.868738   
std     17974.950461   17881.049734   18087.938901   17991.903982   
min         0.920000       0.900000       0.850000       0.890000   
25%        19.602500      19.595000      18.925000      19.277500   
50%       301.425000     295.205000     297.260000     299.720000   
75%      5358.795000    5417.847500    5393.367500    5388.482500   
max    117807.870000  108896.480000  119031.350000  110212.590000   

                  V5             V6             V7             V8  \
count    1212.000000    1212.000000    1212.000000    1212.000000   
mean     8128.297211    8173.030008    8188.582748    8183.641543   
std     17846.757963   17927.114105   18029.562695   18048.582159   
min         0.880000       0.860000       0.870000       0.650000   
25%        19.210000      19.582500      18.690000      19.062500   
50%       295.115000     294.380000     295.935000     290.850000   
75%      5321.987500    5328.040000    5443.977500    5283.655000   
max    113000.470000  116848.390000  115609.240000  118522.320000   

                  V9            V10  ...            V92            V93  \
count    1212.000000    1212.000000  ...    1212.000000    1212.000000   
mean     8154.670066    8120.767574  ...    8120.056815    8125.917409   
std     17982.390713   17900.798206  ...   17773.190621   17758.182403   
min         0.650000       0.620000  ...       0.870000       0.900000   
25%        19.532500      19.285000  ...      19.197500      18.895000   
50%       294.565000     295.160000  ...     297.845000     295.420000   
75%      5378.180000    5319.097500  ...    5355.355000    5386.037500   
max    112895.900000  117798.300000  ...  113858.680000  112948.830000   

                 V94            V95            V96            V97  \
count    1212.000000    1212.000000    1212.000000    1212.000000   
mean     8158.793812    8140.885421    8213.480611    8185.594002   
std     17919.510371   17817.945646   18016.445265   17956.084223   
min         0.870000       0.880000       0.890000       0.890000   
25%        19.237500      19.385000      19.027500      19.135000   
50%       299.155000     293.355000     301.370000     296.960000   
75%      5286.385000    5345.797500    5300.890000    5361.047500   
max    112409.570000  112933.730000  112037.220000  115110.420000   

                 V98            V99           V100        Class  
count    1212.000000    1212.000000    1212.000000  1212.000000  
mean     8140.195355    8192.960891    8156.197376     0.500000  
std     17768.356106   18064.781479   17829.310973     0.500206  
min         0.860000       0.910000       0.890000     0.000000  
25%        19.205000      18.812500      19.145000     0.000000  
50%       300.925000     299.200000     302.275000     0.500000  
75%      5390.850000    5288.712500    5357.847500     1.000000  
max    116431.960000  113291.960000  114533.760000     1.000000  

[8 rows x 101 columns]

In [7]:
print(df.columns.tolist())

['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71', 'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81', 'V82', 'V83', 'V84', 'V85', 'V86', 'V87', 'V88', 'V89', 'V90', 'V91', 'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100', 'Class']


In [8]:
df.shape

(1212, 101)

In [9]:
df['Class'].value_counts()

0    606
1    606
Name: Class, dtype: int64

In [10]:
df.groupby('Class').mean()

V1           V2           V3           V4           V5  \
Class                                                                    
0      7913.333251  7825.339967  7902.497294  7857.032079  7775.610198   
1      8424.850512  8463.272558  8482.810182  8496.705396  8480.984224   

                V6           V7           V8           V9          V10  ...  \
Class                                                                   ...   
0      7875.436337  7804.166584  7722.324802  7793.328416  7686.782046  ...   
1      8470.623680  8572.998911  8644.958284  8516.011716  8554.753102  ...   

               V91          V92          V93          V94          V95  \
Class                                                                    
0      7753.427244  7737.843366  7799.332079  7825.211700  7791.354010   
1      8478.513399  8502.270264  8452.502739  8492.375924  8490.416832   

               V96          V97          V98          V99         V100  
Class                                                                   
0      7927.237112  7874.502343  7844.227459  7875.338713  7855.181172  
1      8499.724109  8496.685660  8436.163251  8510.583069  8457.213581  

[2 rows x 100 columns]

In [11]:
y=df['Class']

In [12]:
y.shape

(1212,)

In [13]:
y

0       0
1       1
2       1
3       0
4       0
       ..
1207    1
1208    0
1209    1
1210    1
1211    0
Name: Class, Length: 1212, dtype: int64

In [14]:
X = df.drop('Class', axis=1)

In [15]:
X.shape

(1212, 100)

In [16]:
X

V1        V2        V3        V4        V5        V6        V7  \
0        39.02     36.49     38.20     38.85     39.38     39.74     37.02   
1         1.83      1.71      1.77      1.77      1.68      1.78      1.80   
2     68177.69  66138.42  72981.88  74304.33  67549.66  69367.34  69169.41   
3     44889.06  39191.86  40728.46  38576.36  45876.06  47034.00  46611.43   
4         5.70      5.40      5.28      5.38      5.27      5.61      6.00   
...        ...       ...       ...       ...       ...       ...       ...   
1207     13.00     12.87     13.27     13.04     13.19     12.53     14.31   
1208     48.66     50.11     48.55     50.43     50.09     49.67     48.95   
1209  10160.65   9048.63   8994.94   9514.39   9814.74  10195.24  10031.47   
1210     34.81     35.07     34.98     32.37     34.16     34.03     33.31   
1211   8489.43   7672.98   9132.14   7985.73   8226.85   8554.28   8838.87   

            V8        V9       V10  ...       V91       V92       V93  \
0        39.53     38.81     38.79  ...     37.57     36.62     36.92   
1         1.70      1.75      1.78  ...      1.71      1.80      1.79   
2     73268.61  74465.84  72503.37  ...  69384.71  73438.88  71053.35   
3     37668.32  40980.89  38466.15  ...  47653.60  42625.67  40684.20   
4         5.38      5.34      5.87  ...      5.52      5.17      5.67   
...        ...       ...       ...  ...       ...       ...       ...   
1207     13.33     13.63     14.55  ...     12.89     12.48     12.15   
1208     48.65     48.63     48.61  ...     47.45     46.93     49.61   
1209  10202.28   9152.99   9591.75  ...  10413.41   9068.11   9191.80   
1210     32.48     35.63     32.48  ...     33.18     32.76     35.03   
1211   8967.24   8635.14   8544.37  ...   7747.70   8609.73   9209.48   

           V94       V95       V96       V97       V98       V99      V100  
0        38.80     38.52     38.07     36.73     39.46     37.50     39.10  
1         1.77      1.74      1.74      1.80      1.78      1.75      1.69  
2     71112.62  74916.48  72571.58  66348.97  71063.72  67404.27  74920.24  
3     46960.73  44546.80  45410.53  47139.44  43095.68  40888.34  39615.19  
4         5.60      5.94      5.73      5.22      5.30      5.73      5.91  
...        ...       ...       ...       ...       ...       ...       ...  
1207     13.15     12.35     13.58     13.86     12.88     13.87     13.51  
1208     47.16     48.17     47.94     49.81     49.89     47.43     47.77  
1209   9275.04   9848.18   9074.17   9601.74  10366.24   8997.60   9305.77  
1210     32.89     31.91     33.85     35.28     32.49     32.83     34.82  
1211   8496.33   8724.01   8219.99   8550.86   8679.43   8389.31   8712.80  

[1212 rows x 100 columns]

In [20]:
import matplotlib.pyplot as plt


In [ ]:
plt.plot(x.iloc[0,:])
plt.title('Valley');

In [ ]:
plt.plot(x.iloc[1,:])
plt.title('Hill');

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
ss= StandardScaler()

In [26]:
X=ss.fit_transform(X)

In [27]:
X

array([[-0.45248681, -0.45361784, -0.45100881, ..., -0.45609618,
        -0.45164274, -0.45545496],
       [-0.45455665, -0.45556372, -0.45302369, ..., -0.45821768,
        -0.45362255, -0.45755405],
       [ 3.33983504,  3.24466709,  3.58338069, ...,  3.5427869 ,
         3.27907378,  3.74616847],
       ...,
       [ 0.11084204,  0.0505953 ,  0.04437307, ...,  0.12533312,
         0.04456025,  0.06450317],
       [-0.45272112, -0.45369729, -0.45118691, ..., -0.45648861,
        -0.45190136, -0.45569511],
       [ 0.01782872, -0.02636986,  0.05196137, ...,  0.03036056,
         0.01087365,  0.03123129]])

In [28]:
 X.shape

(1212, 100)

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=142529)

In [31]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((848, 100), (364, 100), (848,), (364,))

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
lr=LogisticRegression()

In [34]:
lr.fit(X_train,y_train)

LogisticRegression()

In [35]:
y_pred= lr.predict(X_test)

In [36]:
y_pred.shape

(364,)

In [37]:
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,

In [38]:
lr.predict_proba(X_test)

array([[5.07613075e-01, 4.92386925e-01],
       [5.07000838e-01, 4.92999162e-01],
       [5.06376288e-01, 4.93623712e-01],
       [5.07729300e-01, 4.92270700e-01],
       [9.26803095e-01, 7.31969045e-02],
       [5.11847215e-01, 4.88152785e-01],
       [4.89189936e-01, 5.10810064e-01],
       [5.14723614e-01, 4.85276386e-01],
       [5.13453565e-01, 4.86546435e-01],
       [2.06187324e-01, 7.93812676e-01],
       [5.06381373e-01, 4.93618627e-01],
       [6.02111985e-01, 3.97888015e-01],
       [9.98011474e-01, 1.98852650e-03],
       [5.06983212e-01, 4.93016788e-01],
       [5.07079739e-01, 4.92920261e-01],
       [5.49752914e-01, 4.50247086e-01],
       [2.56699819e-01, 7.43300181e-01],
       [4.10893834e-01, 5.89106166e-01],
       [5.07011121e-01, 4.92988879e-01],
       [5.06988112e-01, 4.93011888e-01],
       [5.06972323e-01, 4.93027677e-01],
       [5.06969908e-01, 4.93030092e-01],
       [4.96505861e-01, 5.03494139e-01],
       [4.96698687e-01, 5.03301313e-01],
       [5.070325

In [39]:
from sklearn.metrics import confusion_matrix, classification_report

In [40]:
print(confusion_matrix(y_test,y_pred))

[[177   7]
 [109  71]]


In [41]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.62      0.96      0.75       184
           1       0.91      0.39      0.55       180

    accuracy                           0.68       364
   macro avg       0.76      0.68      0.65       364
weighted avg       0.76      0.68      0.65       364



In [42]:
X_new=df.sample(1)

In [43]:
X_new

V1    V2    V3    V4   V5    V6    V7    V8    V9   V10  ...  V92  \
222  3.17  3.25  3.32  3.26  3.2  3.22  3.25  3.35  3.36  3.34  ...  3.2   

      V93  V94   V95   V96   V97   V98   V99  V100  Class  
222  3.14  3.2  3.35  3.26  3.16  3.27  3.35  3.15      1  

[1 rows x 101 columns]

In [44]:
X_new.shape

(1, 101)

In [45]:
X_new=X_new.drop('Class',axis=1)

In [46]:
X_new

V1    V2    V3    V4   V5    V6    V7    V8    V9   V10  ...   V91  \
222  3.17  3.25  3.32  3.26  3.2  3.22  3.25  3.35  3.36  3.34  ...  3.25   

     V92   V93  V94   V95   V96   V97   V98   V99  V100  
222  3.2  3.14  3.2  3.35  3.26  3.16  3.27  3.35  3.15  

[1 rows x 100 columns]

In [47]:
X_new.shape

(1, 100)

In [48]:
X_neew=ss.fit_transform(X_new)

In [49]:
y_pred_new=lr.predict(X_new)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [50]:
y_pred_new

array([1])

In [51]:
lr.predict_proba(X_new)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


array([[0.06953544, 0.93046456]])